"""
Refresh the MLB game-results cache.

Usage:
    python -m MLB.data_jobs.refresh              # incremental (weekly cron)
    python -m MLB.data_jobs.refresh --force      # re-download everything
    python -m MLB.data_jobs.refresh --no-network # re-parse the cache only

Incremental behaviour: cached seasons cost one conditional GET each (304 =
no download); the season after the newest cached one is probed so the next
Retrosheet annual release is picked up without a code change. After any
download the parsed games table and the coverage report are rebuilt, and the
coverage assertions run either way.
"""

import argparse
import sys
from datetime import date

import pandas as pd
import requests

from .config import (
    COVERAGE_REPORT_PATH,
    EXPECTED_GAMES,
    FIRST_SEASON,
    GAME_COUNT_TOLERANCE,
    GAMES_PATH,
)
from . import gamelogs


def refresh(force: bool = False, network: bool = True) -> pd.DataFrame:
    manifest = gamelogs.load_manifest()

    if network:
        session = requests.Session()
        # Try every season from FIRST_SEASON through the current calendar
        # year. Retrosheet publishes a season after it ends, so the current
        # year is normally 'missing' until the following winter — that is
        # expected, not an error. The statsapi job covers the live season.
        statuses = {}
        for year in range(FIRST_SEASON, date.today().year + 1):
            statuses[year] = gamelogs.download_season(
                year, session, manifest, force=force
            )
        post_statuses = gamelogs.download_postseason(session, manifest, force=force)
        refs = gamelogs.download_reference_files(session)
        gamelogs.save_manifest(manifest)

        downloaded = [y for y, s in statuses.items() if s == "downloaded"]
        missing = [y for y, s in statuses.items() if s == "missing"]
        print(f"seasons downloaded: {downloaded or 'none'}")
        print(f"seasons not yet on the mirror: {missing or 'none'}")
        print(f"postseason files: {post_statuses}")
        print(f"reference files refreshed: {refs}")

    years = gamelogs.cached_seasons()
    if not years:
        sys.exit("No cached seasons and no network — nothing to do.")

    games = gamelogs.build_games_table(years)
    report = coverage_report(games, years)
    with open(COVERAGE_REPORT_PATH, "w") as f:
        f.write(report)
    print(f"\n{len(games):,} games -> {GAMES_PATH}")
    print(f"coverage report -> {COVERAGE_REPORT_PATH}")
    return games


def coverage_report(games: pd.DataFrame, years: list) -> str:
    """
    Per-season coverage table plus hard assertions (house rule 7):
    - every cached season within tolerance of its expected game count;
    - no missing scores, teams, parks, or starting pitchers;
    - both starting pitcher IDs present on every game.
    """
    reg = games[games["game_type"] == "regular"]
    lines = [
        "# MLB games cache — coverage report",
        "",
        f"Generated by `python -m MLB.data_jobs.refresh`. "
        f"{len(games):,} games total ({len(reg):,} regular season, "
        f"{len(games) - len(reg):,} postseason), seasons {years[0]}–{years[-1]}.",
        "",
        "| season | games | expected | extras | missing SP | missing ump | avg R/G |",
        "|---|---|---|---|---|---|---|",
    ]
    problems = []
    for year in years:
        g = reg[reg["season"] == year]
        expected = EXPECTED_GAMES.get(year)
        n = len(g)
        missing_sp = int(g["home_sp_id"].isna().sum() + g["away_sp_id"].isna().sum())
        missing_ump = int(g["ump_hp_id"].isna().sum())
        extras = int(g["extra_innings"].sum())
        rpg = (g["home_score"] + g["away_score"]).mean()
        lines.append(
            f"| {year} | {n} | {expected} | {extras} | {missing_sp} "
            f"| {missing_ump} | {rpg:.2f} |"
        )
        # Symmetric window: a season can run a few games short (rainouts
        # never made up) or a couple over (game-163 tiebreakers, tie games
        # that were later replayed).
        if expected and abs(n - expected) > GAME_COUNT_TOLERANCE:
            problems.append(f"{year}: {n} games, expected ~{expected}")
        if missing_sp:
            problems.append(f"{year}: {missing_sp} missing starting-pitcher IDs")

    for col in ("home_score", "away_score", "home_team", "away_team", "park_id"):
        nulls = int(games[col].isna().sum())
        if nulls:
            problems.append(f"{nulls} null values in {col}")

    lines += ["", "## Assertions", ""]
    if problems:
        lines += [f"- **FAIL** {p}" for p in problems]
        report = "\n".join(lines) + "\n"
        with open(COVERAGE_REPORT_PATH, "w") as f:
            f.write(report)
        raise AssertionError(
            "coverage assertions failed:\n" + "\n".join(problems)
        )
    lines.append("- all seasons within tolerance; no null scores/teams/parks; "
                 "all starting pitchers present")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true",
                        help="re-download all seasons")
    parser.add_argument("--no-network", action="store_true",
                        help="re-parse the existing cache without downloading")
    args = parser.parse_args()
    refresh(force=args.force, network=not args.no_network)


if __name__ == "__main__":
    main()
